global using System;
global using System.Linq;
global using System.Windows.Forms;
global using System.Data.SqlClient;
global using Microsoft.Win32;
global using SepantaDBConnector.Properties;
global using SepantaDBConnector.Company;
global using SepantaDBConnector.App;
global using SepantaDBConnector.Connection;