//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SepantaDBConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SepantaDBConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Create .
        /// </summary>
        internal static string CantCreate {
            get {
                return ResourceManager.GetString("CantCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection succeeded..
        /// </summary>
        internal static string Con_TestSucseeded {
            get {
                return ResourceManager.GetString("Con_TestSucseeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Not Sucsessfully.
        /// </summary>
        internal static string ConnectionNotSaved {
            get {
                return ResourceManager.GetString("ConnectionNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Sucsessfully.
        /// </summary>
        internal static string ConnectionSaved {
            get {
                return ResourceManager.GetString("ConnectionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created .
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Successfully..
        /// </summary>
        internal static string CreatedSucces {
            get {
                return ResourceManager.GetString("CreatedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of is empty..
        /// </summary>
        internal static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CentralConnection.
        /// </summary>
        internal static string reg_CentralConnection {
            get {
                return ResourceManager.GetString("reg_CentralConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string reg_Description {
            get {
                return ResourceManager.GetString("reg_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sepanta.
        /// </summary>
        internal static string reg_Sepanta {
            get {
                return ResourceManager.GetString("reg_Sepanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software.
        /// </summary>
        internal static string reg_Software {
            get {
                return ResourceManager.GetString("reg_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string reg_Version {
            get {
                return ResourceManager.GetString("reg_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepanta Connection.
        /// </summary>
        internal static string SepantaConnection {
            get {
                return ResourceManager.GetString("SepantaConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SepantaDBConnector {
            get {
                object obj = ResourceManager.GetObject("SepantaDBConnector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
